name: Deploy to Vultr VPS

on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push files to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REPO_DIRECTORY }}
            git pull
          script-stop: true
      - name: Build Nuxt.js with Yarn
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REPO_DIRECTORY }}
            yarn install
            yarn build
          script-stop: true
      - name: Deploy site with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REPO_DIRECTORY }}
            pm2 start
          script-stop: true
